name: Publish extensions to open-vsx.org

on:
  schedule:
    # Run at 03:03 UTC every day.
    - cron:  '3 3 * * *'
  workflow_dispatch:
    inputs:
      extensions:
        description: "Comma separated list of extensions to publish"
        required: false
        default: ""
      skipPublish:
        description: 'Skip publishing to Open VSX, only build extensions'
        type: boolean
        required: false
        default: false
      forcefullyPublish:
        description: 'Force publish to OpenVSX, even if version is already published'
        type: boolean
        required: false
        default: false

jobs:
  publish_extensions:
    env:
      EXTENSIONS: ${{ github.event.inputs.extensions }}
      SKIP_PUBLISH: ${{ github.event.inputs.skipPublish }}
      FORCE: ${{ github.event.inputs.forcefullyPublish }}
    name: node publish-extensions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3.2.0
      with:
        node-version: '14.x'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - run: npm install
    - run: npm i -g vsce
    - run: node publish-extensions
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: node report-extensions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: report
        path: |
          /tmp/stat.json
          /tmp/result.log
    - name: Slack Notification
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.GITPOD_SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
