name: Publish extensions to open-vsx.org

on:
  schedule:
    # Run at 03:03 UTC every day.
    - cron:  '3 3 * * *'
  workflow_dispatch:

jobs:
  publish_extensions:
    env:
      FAILED_EXTENSIONS: justusadam.language-haskell, ms-toolsai.jupyter
    name: node publish-extensions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - run: npm install
    - run: npm install --global yarn
    - run: node publish-extensions
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}
    - run: node report-extensions
