name: Publish an extensions from a vsix file

on:
  workflow_dispatch:
    inputs:
      extensions:
        description: "URL of the `.vsix`"
        required: true
      namespace:
        description: "If a namespace does not exist for the author, provide it here"
        required: false

jobs:
  publish:
    name: node publish-extensions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3.2.0
        with:
          node-version: "14.x"
      - name: Download extension file
        run: wget -O extension.vsix ${{ github.event.inputs.extensions }}
      - name: Create OpenVSX namespace
        if: ${{ github.event.inputs.namespace }}
        run: npx ovsx create-namespace ${{ github.event.inputs.namespace }} -p ${{ secrets.OVSX_PAT }}
      - name: Publish to OpenVSX
        run: npx ovsx publish extension.vsix  -p ${{ secrets.OVSX_PAT }}
