name: Validate extensions

on: [push, pull_request]

jobs:
  validate_extensions:
    name: node validate-extensions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: node validate-extensions
